baseURL = "https://www.axivo.com/"
languageCode = "en-us"
title = "AXIVO"
disableHugoGeneratorInject = true
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm"]

[params]
    author = "AXIVO"
    description = "Imagine. Create."

    [[params.links]]
        icon = "github"
        title = "Github"
        url = "https://github.com/axivo"
