name: Deploy Documentation
on:
  push:
    branches:
      - main
  workflow_dispatch:
concurrency:
  cancel-in-progress: false
  group: pages
defaults:
  run:
    shell: bash
jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          cache: false
          go-version: 1.22.3
      - name: Setup Hugo
        run: sudo snap install --channel=extended/stable hugo
      - name: Configure Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Build Content
        env:
          HUGO_ENV: production
          HUGO_ENVIRONMENT: production
          TZ: America/New_York
        run: |
          hugo --gc --minify -s ./docs --config ../global/hugo.yaml,./hugo.yaml
          hugo --gc --minify -s ./k3s-cluster --config ../global/hugo.yaml,./hugo.yaml
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
  deploy:
    name: Deploy to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v4
permissions:
  contents: read
  pages: write
  id-token: write
