name: Deploy Documentation
on:
  push:
    branches:
      - main
    paths:
      - docs/**
      - k3s-cluster/**
  workflow_dispatch:
concurrency:
  cancel-in-progress: false
  group: pages
defaults:
  run:
    shell: bash
jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          cache: false
          go-version: 1.22.2
      - name: Setup Hugo
        env:
          HUGO_URL: https://github.com/gohugoio/hugo/releases/download
          HUGO_VERSION: 0.125.4
        run: |
          wget -O ${{ runner.temp }}/hugo.deb \
            ${HUGO_URL}/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb
          sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Configure Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Build Content
        env:
          HUGO_ENV: production
          HUGO_ENVIRONMENT: production
          TZ: America/New_York
        run: |
          hugo --gc --minify -s ./docs -b "${{ steps.pages.outputs.base_url }}/"
          install -d ./docs/public/k3s-cluster
          hugo --gc --minify -s ./k3s-cluster -d ./docs/public/k3s-cluster/ -b "${{ steps.pages.outputs.base_url }}/k3s-cluster/"
          ls -lah ./docs/public/k3s-cluster
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/public
  deploy:
    name: Deploy to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v4
permissions:
  contents: read
  pages: write
  id-token: write
