name: Deploy Documentation
on:
  push:
    branches:
      - main
    paths:
      - docs/**
      - k3s-cluster/**
  workflow_dispatch:
concurrency:
  cancel-in-progress: false
  group: pages
defaults:
  run:
    shell: bash
jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          cache: false
          go-version: 1.22.2
      - name: Setup Hugo
        env:
          HUGO_VERSION: 0.125.4
        run: snap install hugo --channel=${HUGO_VERSION}/stable
      - name: Configure Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Build Content
        env:
          HUGO_ENV: production
          HUGO_ENVIRONMENT: production
          TZ: America/New_York
        run: |
          hugo --gc --minify -s ./docs
          hugo --gc --minify -s ./k3s-cluster -d "$(pwd)/docs/public/k3s-cluster"
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/public
  deploy:
    name: Deploy to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v4
permissions:
  contents: read
  pages: write
  id-token: write
